# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Tue Nov  6 13:10:02 2018
#

import json
import os
import sys
import urllib.request
import wx

from SaveData import SaveData

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

# Name of the script for putting in error messages, probably just python-omdb.py
NAME = os.path.basename(sys.argv[0])

# Read their fokin saved data
# Obviously this will actually be from a file later
SAVE_DATA = SaveData()

# Gets info for a movie title
# Just as a string for now for testing
# Returns an empty string if something went wrong
# TODO Implement this properly
def get_info(title):
    # Error handling is for pussies!
    # (error handling is not actually for pussies, fix this)
    response = json.loads(urllib.request.urlopen(f'http://www.omdbapi.com/?apikey={SAVE_DATA.key}&t={urllib.parse.quote_plus(title)}').read().decode('utf-8'))

    if response["Response"] == "False":
        print(f'{NAME}: error: {response["Error"]}', file=sys.stderr)
        return str()

    return f'Title: {response["Title"]}\nYear: {response["Year"]}\nActors: {response["Actors"]}\nPlot: {response["Plot"]}'

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.RESIZE_BORDER
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1092, 1057))
        self.list_box_saved = wx.ListBox(self, wx.ID_ANY, choices=["Entry 1", "Entry 2", "Entry 3"])
        self.button_find = wx.Button(self, wx.ID_FIND, "")
        self.text_ctrl_find = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_add = wx.Button(self, wx.ID_ADD, "")
        self.button_delete = wx.Button(self, wx.ID_DELETE, "")
        self.label_info = wx.StaticText(self, wx.ID_ANY, "Film information goes here")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_LISTBOX, self.list_box_clicked, self.list_box_saved)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle("python-omdb")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_all = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_right = wx.BoxSizer(wx.VERTICAL)
        sizer_list = wx.BoxSizer(wx.VERTICAL)
        sizer_controls = wx.BoxSizer(wx.HORIZONTAL)
        sizer_list.Add(self.list_box_saved, 1, wx.EXPAND, 0)
        sizer_controls.Add(self.button_find, 0, wx.ALIGN_CENTER | wx.ALL, 3)
        sizer_controls.Add(self.text_ctrl_find, 1, wx.ALL, 3)
        sizer_controls.Add(self.button_add, 0, wx.ALIGN_CENTER | wx.ALL, 3)
        sizer_controls.Add(self.button_delete, 0, wx.ALIGN_CENTER | wx.ALL, 3)
        sizer_list.Add(sizer_controls, 0, wx.EXPAND, 0)
        sizer_all.Add(sizer_list, 1, wx.EXPAND, 0)
        self.sizer_right.Add(self.label_info, 0, wx.ALL | wx.EXPAND, 3)
        sizer_all.Add(self.sizer_right, 1, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_all)
        self.Layout()
        # end wxGlade

    def list_box_clicked(self, event):  # wxGlade: MainFrame.<event_handler>

        result = get_info(event.GetString())

        if not result:
            self.label_info.SetLabel('<ERROR>')
        else:
            self.label_info.SetLabel(result)

        self.sizer_right.Layout() # reloads everything to show the new label text

# end of class MainFrame

app = wx.PySimpleApp()
frame_main = MainFrame(None, wx.ID_ANY, "")

# Populate the listbox with the saved films
frame_main.list_box_saved.Set(SAVE_DATA.films)

app.SetTopWindow(frame_main)
frame_main.Show()
app.MainLoop()
